const spanishNames = {
  genesis: 'Génesis',
  exodus: 'Éxodo',
  leviticus: 'Levítico',
  numbers: 'Números',
  deuteronomy: 'Deuteronomio',
  joshua: 'Josué',
  judges: 'Jueces',
  ruth: 'Rut',
  '1-samuel': '1 Samuel',
  '2-samuel': '2 Samuel',
  '1-kings': '1 Reyes',
  '2-kings': '2 Reyes',
  '1-chronicles': '1 Crónicas',
  '2-chronicles': '2 Crónicas',
  ezra: 'Esdras',
  nehemiah: 'Nehemías',
  esther: 'Ester',
  job: 'Job',
  psalms: 'Salmos',
  proverbs: 'Proverbios',
  ecclesiastes: 'Eclesiastés',
  'song-of-solomon': 'Cantares',
  isaiah: 'Isaías',
  jeremiah: 'Jeremías',
  lamentations: 'Lamentaciones',
  ezekiel: 'Ezequiel',
  daniel: 'Daniel',
  hosea: 'Oseas',
  joel: 'Joel',
  amos: 'Amós',
  obadiah: 'Abdías',
  jonah: 'Jonás',
  micah: 'Miqueas',
  nahum: 'Nahúm',
  habakkuk: 'Habacuc',
  zephaniah: 'Sofonías',
  haggai: 'Hageo',
  zechariah: 'Zacarías',
  malachi: 'Malaquías',
  matthew: 'Mateo',
  mark: 'Marcos',
  luke: 'Lucas',
  john: 'Juan',
  acts: 'Hechos',
  romans: 'Romanos',
  '1-corinthians': '1 Corintios',
  '2-corinthians': '2 Corintios',
  galatians: 'Gálatas',
  ephesians: 'Efesios',
  philippians: 'Filipenses',
  colossians: 'Colosenses',
  '1-thessalonians': '1 Tesalonicenses',
  '2-thessalonians': '2 Tesalonicenses',
  '1-timothy': '1 Timoteo',
  '2-timothy': '2 Timoteo',
  titus: 'Tito',
  philemon: 'Filemón',
  hebrews: 'Hebreos',
  james: 'Santiago',
  '1-peter': '1 Pedro',
  '2-peter': '2 Pedro',
  '1-john': '1 Juan',
  '2-john': '2 Juan',
  '3-john': '3 Juan',
  jude: 'Judas',
  revelation: 'Apocalipsis',
};

const baseBooks = [
  { id: 'genesis', testament: 'old' },
  { id: 'exodus', testament: 'old' },
  { id: 'leviticus', testament: 'old' },
  { id: 'numbers', testament: 'old' },
  { id: 'deuteronomy', testament: 'old' },
  { id: 'joshua', testament: 'old' },
  { id: 'judges', testament: 'old' },
  { id: 'ruth', testament: 'old' },
  { id: '1-samuel', testament: 'old' },
  { id: '2-samuel', testament: 'old' },
  { id: '1-kings', testament: 'old' },
  { id: '2-kings', testament: 'old' },
  { id: '1-chronicles', testament: 'old' },
  { id: '2-chronicles', testament: 'old' },
  { id: 'ezra', testament: 'old' },
  { id: 'nehemiah', testament: 'old' },
  { id: 'esther', testament: 'old' },
  { id: 'job', testament: 'old' },
  { id: 'psalms', testament: 'old' },
  { id: 'proverbs', testament: 'old' },
  { id: 'ecclesiastes', testament: 'old' },
  { id: 'song-of-solomon', testament: 'old' },
  { id: 'isaiah', testament: 'old' },
  { id: 'jeremiah', testament: 'old' },
  { id: 'lamentations', testament: 'old' },
  { id: 'ezekiel', testament: 'old' },
  { id: 'daniel', testament: 'old' },
  { id: 'hosea', testament: 'old' },
  { id: 'joel', testament: 'old' },
  { id: 'amos', testament: 'old' },
  { id: 'obadiah', testament: 'old' },
  { id: 'jonah', testament: 'old' },
  { id: 'micah', testament: 'old' },
  { id: 'nahum', testament: 'old' },
  { id: 'habakkuk', testament: 'old' },
  { id: 'zephaniah', testament: 'old' },
  { id: 'haggai', testament: 'old' },
  { id: 'zechariah', testament: 'old' },
  { id: 'malachi', testament: 'old' },
  { id: 'matthew', testament: 'new' },
  { id: 'mark', testament: 'new' },
  { id: 'luke', testament: 'new' },
  { id: 'john', testament: 'new' },
  { id: 'acts', testament: 'new' },
  { id: 'romans', testament: 'new' },
  { id: '1-corinthians', testament: 'new' },
  { id: '2-corinthians', testament: 'new' },
  { id: 'galatians', testament: 'new' },
  { id: 'ephesians', testament: 'new' },
  { id: 'philippians', testament: 'new' },
  { id: 'colossians', testament: 'new' },
  { id: '1-thessalonians', testament: 'new' },
  { id: '2-thessalonians', testament: 'new' },
  { id: '1-timothy', testament: 'new' },
  { id: '2-timothy', testament: 'new' },
  { id: 'titus', testament: 'new' },
  { id: 'philemon', testament: 'new' },
  { id: 'hebrews', testament: 'new' },
  { id: 'james', testament: 'new' },
  { id: '1-peter', testament: 'new' },
  { id: '2-peter', testament: 'new' },
  { id: '1-john', testament: 'new' },
  { id: '2-john', testament: 'new' },
  { id: '3-john', testament: 'new' },
  { id: 'jude', testament: 'new' },
  { id: 'revelation', testament: 'new' },
];

const bibleBooks = baseBooks.map(book => ({
  ...book,
  name: spanishNames[book.id],
}));

module.exports = { bibleBooks };
